### ISSUE TITLE
针对Docker部署的文档调整

### ISSUE THREAD

**Issue by popjdh** [carrot-hu23/dst-admin-go#80]
Docker部署经常存在如下两大问题:
- 服务器启动无应答
- 饥荒服务启动缓慢

### 服务器启动无应答

docker部署时, 需要将相关端口开放. 至少应当开放面板端口`8082/TCP`, 地上端口`10998/UDP`, 地下端口`10999/UDP`.

而现有部署文档中只提及了端口`8082/TCP`.

### 饥荒服务启动缓慢

Docker现在默认的nofile已经达到1073741816. 类似的例子可以参考[SOF](https://stackoverflow.com/questions/71828013/docker-container-has-a-too-large-file-descriptor-limit-ulimit-n).

这会导致GNU Screen运行十分缓慢, 进而影响对饥荒服务的启动与操纵. 

### 解决方案

`docker`:

```sh
docker run -d --name dst -p 8082:8082 -p 10998:10998/udp -p 10999:10999/udp --ulimit nofile=65536:65536 hujinbo23/dst-admin-go:1.3.0
```

`docker-compose`:

```yml
version: "3"

services:
  dst:
    container_name: dst
    image: hujinbo23/dst-admin-go:1.3.0
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8082:8082
      - 10998:10998/udp
      - 10999:10999/udp
    restart: unless-stopped
```

**Comment by carrot-hu23** [comment]
**前置文件**
```
# 创建 first 文件
touch ~/dstsave/first
touch ~/dstsave/dst-db

# 创建 ~/dstsave/password.txt 文件
echo "username = admin
password = 123456
displayName = admin
photoURL = 
email = xxx" > ~/dstsave/password.txt
```

**docker-compose.yml 参考**

```
version: '3'
services:
  dst-admin-go:
    image: hujinbo23/dst-admin-go:1.5.1
    port:
      - "8084:8082"
      - "10999:10999"
      - "10998:10998"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PWD}/dstsave:/root/.klei/DoNotStarveTogether
      - ${PWD}/dstsave/back:/app/backup
      - ${PWD}/steamcmd:/app/steamcmd
      - ${PWD}/dst-dedicated-server:/app/dst-dedicated-server
      - ${PWD}/dstsave/dst-db:/app/dst-db
      - ${PWD}/dstsave/password.txt:/app/password.txt
      - ${PWD}/dstsace/first:/app/first
```

+ 容器存档启动路径: /root/.klei/DoNotStarveTogether
+ 容器存档备份路径: /app/backup
+ 容器存档模组路径: /app/mod
+ 容器服务日志路径: app/dst-db  这是一个文件
+ 容器服务日志路径: /app/dst-admin-go.log
+ 容器启动饥荒路径: /app/dst-dedicated-server
+ 容器启动steamcmd：/app/steamcmd
+ first 代表是否第一次登录，如果没有这个文件会跳转到初始化界面设置账号

挂载含义参考 https://hub.docker.com/repository/docker/hujinbo23/dst-admin-go/general
